openapi: 3.0.1
info:
  title: monster-chasme
  x-cortex-tag: monster-chasme
  x-cortex-custom-metadata:
    alignment: chaotic-evil
    type: fiend
    challenge_rating: 6
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-chasme
      alias: github-token-test
